project:
  type: website
  output-dir: docs
website:
  page-navigation: true
  title: "Course Materials for Stat 100 F23"
  navbar:
    left:
    - text: "Homepage"
      icon: fa-home
      href: index.qmd
    - text: "Slides (First Half)"
      icon: fa-chart-area
      menu: 
        - text: "Week 1 Wed"
          icon: fa-file
          href: stat100_wk01wed.qmd

format:
  html:
    theme: yeti
    css: ["styles.css", "more.css"]
    toc: true

editor: visual

